export const metadata = {
    title: "Home Page",
    description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
    return (
        <>
            {children}
        </>
    );
}
