export const metadata = {
    title: "Auth Page",
    description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
    return (
        <>
            {children}
        </>
    );
}
